**LABORATORIO 5**

In [1]:
import numpy as np
import pylab as plt
import math

**Exponencial, serie alternante (serieEn)**

In [2]:
def exponencial_negativo(x,k):

    N = np.arange(0,k,1)
    Sumador = 0

    for n in N:

        Sumador = Sumador + ((-1)**int(n)) * (x**int(n)) / math.factorial(int(n))

    return Sumador

In [3]:
exponencial_negativo(-1,1000), np.exp(-0.9)

(2.7182818284590455, 0.4065696597405991)

In [4]:
def exponencial_negativo_n(x):

    N = np.arange(0,10000,1)

    Sumador = 0
    Sumando = 0
    nn = 0
    


    for n in N:

        if np.abs(Sumando) < np.abs((Sumador * (10**(-7)))):
            break

        else:
             
            Sumador = Sumador + ((-1)**int(n)) * (x**int(n)) / math.factorial(int(n))
            Sumando = ((-1)**int(n)) * (x**int(n)) / math.factorial(int(n))
            nn = n

    return Sumador, nn

In [5]:
exponencial_negativo_n(0.9)

(0.4065696591893227, 11)

In [6]:
x = 10

exponencial_negativo_n(x), exponencial_negativo(x,x -1), np.exp(-x)

((4.539992975340805e-05, 46), 1342.5873015873017, 4.5399929762484854e-05)

In [7]:
def exponecial(x,k):

    N = np.arange(0,k,1)
    Sumador = 0

    for n in N:

        Sumador = Sumador + (x**int(n)) / math.factorial(int(n))

    return Sumador


In [8]:
x = 10

1/exponecial(x,x-1), exponencial_negativo(x,x -1), 1/np.exp(x)

(0.00013640999214018616, 1342.5873015873017, 4.539992976248485e-05)

In [9]:
X1 = np.arange(0,10 + 0.2 ,0.2)
F1 = np.zeros(len(X1))

M1 = np.arange(0,len(X1),1)

for m1 in M1:
    f1,n1 = exponencial_negativo_n(float(X1[m1]))
    F1[m1] = f1

F1

array([1.00000000e+00, 8.18730753e-01, 6.70320047e-01, 5.48811635e-01,
       4.49328966e-01, 3.67879439e-01, 3.01194213e-01, 2.46596963e-01,
       2.01896519e-01, 1.65298888e-01, 1.35335284e-01, 1.10803158e-01,
       9.07179523e-02, 7.42735788e-02, 6.08100623e-02, 4.97870685e-02,
       4.07622039e-02, 3.33732696e-02, 2.73237227e-02, 2.23707717e-02,
       1.83156390e-02, 1.49955770e-02, 1.22773398e-02, 1.00518358e-02,
       8.22974702e-03, 6.73794702e-03, 5.51656448e-03, 4.51658091e-03,
       3.69786373e-03, 3.02755479e-03, 2.47875215e-03, 2.02943065e-03,
       1.66155727e-03, 1.36036802e-03, 1.11377516e-03, 9.11881960e-04,
       7.46585812e-04, 6.11252770e-04, 5.00451429e-04, 4.09734982e-04,
       3.35462626e-04, 2.74653566e-04, 2.24867326e-04, 1.84105793e-04,
       1.50733076e-04, 1.23409805e-04, 1.01039401e-04, 8.27240656e-05,
       6.77287373e-05, 5.54515983e-05, 4.53999298e-05])

In [10]:
f,n = exponencial_negativo_n(10)

f, np.exp(-10)

(4.539992975340805e-05, 4.5399929762484854e-05)

In [11]:
X2 = np.arange(10,100, 0.2)
N2 = []
F2 = []
M2 = np.arange(0,len(X2),1)
f = 10


for m2 in M2:
    
    f2,n2 = exponencial_negativo_n(float(X2[m2]))
    F2.append(f2), N2.append(n2)

    if f < f2:
        break 

    else:
        f = f2 

np.array(F2)

array([4.53999298e-05, 3.71703182e-05, 3.04324825e-05, 2.49160106e-05,
       2.03995023e-05, 1.67017004e-05, 1.36741941e-05, 1.11954830e-05,
       9.16608916e-06, 7.50455920e-06, 6.14421493e-06, 5.03045638e-06,
       4.11859565e-06, 3.37202156e-06, 2.76077863e-06, 2.26034150e-06,
       1.85059718e-06, 1.51514067e-06, 1.24047267e-06, 1.01563985e-06,
       8.31563087e-07, 6.80815430e-07, 5.57389833e-07, 4.56396072e-07,
       3.73628379e-07, 3.05948666e-07, 2.50411486e-07, 2.05026541e-07,
       1.67937107e-07, 1.37329655e-07, 1.12610959e-07, 9.24227634e-08,
       7.54790789e-08, 6.14748692e-08, 5.01279977e-08, 4.16731340e-08,
       3.33199243e-08, 2.74030333e-08, 2.20156017e-08, 1.74743278e-08,
       1.55448649e-08, 1.06697452e-08, 1.11721378e-08])

In [12]:
f2,n2 = exponencial_negativo_n(10*4*0.2 + 5*0.2 + 10)
f3,n3 = exponencial_negativo_n(10*4*0.2 + 6*0.2 + 10)
f22, f33 = np.exp(-(10*4*0.2 + 5*0.2 + 10)), np.exp(-(10*4*0.2 + 6*0.2 + 10))

f2 < f3, f2, f3, f22, f33

(True,
 1.982201980788498e-09,
 1.4484993259195466e-08,
 5.602796437537268e-09,
 4.587181746647525e-09)

In [13]:
def exponencial_n(x):

    N = np.arange(0,10000,1)

    Sumador = 0
    Sumando = 0
    nn = 0

    for n in N:

        if np.abs(Sumando) < np.abs((Sumador * (10**(-7)))):
            break

        else:
             
            Sumador = Sumador + (x**int(n)) / math.factorial(int(n))
            Sumando = (x**int(n)) / math.factorial(int(n))
            nn = n

    return Sumador, nn

In [14]:
X1 = np.arange(0,10 + 0.2 ,0.2)
F1 = np.zeros(len(X1))

M1 = np.arange(0,len(X1),1)

for m1 in M1:
    f1,n1 = exponencial_n(X1[m1])
    F1[m1] = 1/f1

F1

array([1.00000000e+00, 8.18730755e-01, 6.70320046e-01, 5.48811637e-01,
       4.49328965e-01, 3.67879441e-01, 3.01194214e-01, 2.46596965e-01,
       2.01896518e-01, 1.65298890e-01, 1.35335284e-01, 1.10803160e-01,
       9.07179538e-02, 7.42735796e-02, 6.08100631e-02, 4.97870685e-02,
       4.07622044e-02, 3.33732701e-02, 2.73237227e-02, 2.23707724e-02,
       1.83156391e-02, 1.49955772e-02, 1.22773400e-02, 1.00518360e-02,
       8.22974712e-03, 6.73794712e-03, 5.51656446e-03, 4.51658101e-03,
       3.69786383e-03, 3.02755479e-03, 2.47875224e-03, 2.02943066e-03,
       1.66155731e-03, 1.36036805e-03, 1.11377517e-03, 9.11881992e-04,
       7.46585818e-04, 6.11252775e-04, 5.00451452e-04, 4.09734986e-04,
       3.35462638e-04, 2.74653574e-04, 2.24867329e-04, 1.84105800e-04,
       1.50733078e-04, 1.23409807e-04, 1.01039403e-04, 8.27240673e-05,
       6.77287387e-05, 5.54516003e-05, 4.53999309e-05])

In [15]:
X2 = np.arange(10,99 + 0.5,0.5)
N2 = np.zeros(len(X2))
F2 = np.zeros(len(X2))
M2 = np.arange(0,len(X2),1)

for m2 in M2:
    f2,n2 = exponencial_n(float(X2[m2]))
    F2[m2],N2[m2] = 1/f2, n2

F2, N2

(array([4.53999309e-05, 2.75364500e-05, 1.67017011e-05, 1.01300938e-05,
        6.14421246e-06, 3.72665334e-06, 2.26032950e-06, 1.37095914e-06,
        8.31528745e-07, 5.04347676e-07, 3.05902328e-07, 1.85539147e-07,
        1.12535180e-07, 6.82560365e-08, 4.13993786e-08, 2.51099923e-08,
        1.52299807e-08, 9.23745016e-09, 5.60279669e-09, 3.39826795e-09,
        2.06115369e-09, 1.25015295e-09, 7.58256084e-10, 4.59905559e-10,
        2.78946820e-10, 1.69189805e-10, 1.02618803e-10, 6.22414494e-11,
        3.77513470e-11, 2.28973493e-11, 1.38879448e-11, 8.42346422e-12,
        5.10908926e-12, 3.09881925e-12, 1.87952895e-12, 1.13999192e-12,
        6.91440043e-13, 4.19379601e-13, 2.54366582e-13, 1.54281129e-13,
        9.35762340e-14, 5.67568570e-14, 3.44247734e-14, 2.08796803e-14,
        1.26641661e-14, 7.68120529e-15, 4.65888645e-15, 2.82575744e-15,
        1.71390859e-15, 1.03953809e-15, 6.30511714e-16, 3.82424682e-16,
        2.31952302e-16, 1.40686181e-16, 8.53304810e-17, 5.175555

In [16]:
f,n = exponencial_n(700)

exponencial_negativo_n(67), np.exp(-700), 1/f, n

((-1806559128062.4675, 166), 9.85967654375977e-305, 9.859681194365e-305, 833)

**Cancelación sustractiva**

In [36]:
def S1(k):

    N = np.arange(1,2*k,1)
    Sumador = 0 

    for n in N:

        Sumador = Sumador + (((-1)**int(n)) * (int(n) / (int(n) + 1 )))
    
    return Sumador

def S2(k):

    N = np.arange(1,k,1)
    Sumador_n = 0 
    Sumador_p = 0

    for n in N:
        
        Sumador_n = Sumador_n + (2*int(n) - 1) / (2*int(n))
        Sumador_p = Sumador_p + (2*int(n)) / (2*int(n) + 1)

    return Sumador_p - Sumador_n

def S3(k):

    N = np.arange(1,k,1)
    Sumador = 0

    for n in N:

        Sumador = Sumador + 1 / (2*int(n) * (2*int(n) + 1))
    
    return Sumador

In [38]:
k = 80

S1(k),S2(k),S3(k)

(-0.690031945994226, 0.30371805400575624, 0.3037180540057747)