1. Calcular el polinomio caracteristico, los autovalores y autvectores propios de la siguiente matrices, comprobar con la solucion analitica:

a.
    \begin{bmatrix}
    1 & -1 & 4 \\
    3 & 2 & -1 \\
    2 & 1 & -1\
    \end{bmatrix}



b. Matriz con autovalores imaginarios
    \begin{bmatrix}
    3 & -5 \\
    1 & -1 \\
    \end{bmatrix}


In [4]:
import numpy as np
import sympy as sp
import scipy as sc

In [5]:
## variable simbolica.

x = sp.Symbol("x")

M = np.array([
    [1,-1,4],
    [3,2,-1],
    [2,1,-1]
])

e,v = np.linalg.eig(M)

M2 = np.array([

    [3,-5],
    [1,-1]
])

v

array([[ 0.40824829,  0.57735027,  0.23570226],
       [ 0.81649658, -0.57735027, -0.94280904],
       [ 0.40824829, -0.57735027, -0.23570226]])

In [6]:
## esta funcion me calcula el det para una matriz 2x2
def det2x2(M):
  val = M[0][0]  * M[1][1]
  val2 = M[1][0] * M[0][1]
  det = val - val2
  return det

## esta funcion me calcula el det para una matriz 3x3

def det3x3(M):
  T1 = M[0,0]*det2x2(M[1:3:1,1:3:1])
  T2 = M[0,1]*det2x2(M[1:3:1,0:3:2])
  T3 = M[0,2]*det2x2(M[1:3:1,0:2:1])
  det = T1 - T2 + T3
  return det

## esta funcion me calcula polinomio caracteristico de una matriz 3x3

def poly_caract(M):
  I = np.identity(np.shape(M)[0])
  newM = M-x*I
  poly = det3x3(newM)
  return poly

## esta funcion me calcula los autovalores de una matriz 3x3

def autovalores(M):
  poly = poly_caract(M)
  sol = sp.solve(poly,x)
  return sol


def poly_caract2x2(M):
  x = sp.Symbol("x")
  I = np.identity(np.shape(M)[0])
  newM = M - x*I
  poly = det2x2(newM)
  return poly

def autovalores2x2(M):
  poly = poly_caract2x2(M)
  sol = sp.solve(poly,x)
  return sol

In [68]:
## aquí se pondrá todo lo relacionado con el gauss jordan requerido y generalizado para matrices homogeneas.


def sum_filas_escalar(M,R1,R2,a,b):
  R1 = R1-1
  R2 = R2-1
  B = np.copy(M)
  B[R1] = a*M[R1]+b*M[R2]
  return B

def mul_escalar(M,R1,a):
  R1 = R1-1
  B = np.copy(M)
  B[R1] = a*M[R1]
  return B
def intercambio(M,R1,R2):
  R1 = R1-1
  R2 = R2-1
  B = np.copy(M)
  B[R1] = M[R2]
  B[R2] = M[R1]
  return B

def gauss_jordan(M):
  x = sp.Symbol("x")
  B = np.copy(M)
  if M[0][0] !=0:
    if M[1][0] !=0:
      resul = sp.solve(x*M[0][0]-M[1][0],x)
      resul = float(resul[0])
      M = sum_filas_escalar(M,2,1,1,-resul)
    if M[2][0] !=0:
      resul = sp.solve(x*M[0][0]-M[2][0],x)
      resul = float(resul[0])
      M = sum_filas_escalar(M,3,1,1,-resul)
  if M[0][0] == 0 and M[1][0] !=0:
    M = intercambio(M,1,2)
    if M[2][0] !=0:
      resul = sp.solve(x*M[0][0]-M[2][0],x)
      resul = float(resul[0])
      M = sum_filas_escalar(M,3,1,1,-resul)
  if M[0][0] == 0 and M[1][0] ==0:
    M = intercambio(M,1,3)
  if M[1][1] != 0 and M[2][1] !=0:
    resul = sp.solve(x*M[1][1]-M[2][1],x)
    resul = float(resul[0])
    M = sum_filas_escalar(M,3,2,1,-resul)
  if M[1][1] == 0 and M[2][1] !=0:
    M = intercambio(M,2,3)
  return M


def solution(M):
  C = sp.solve(x*M[2][2]-M[2][3],x)
  C = float(C[0])
  B = sp.solve(x*M[1][1]+M[1][2]*C-M[1][3],x)
  B = float(B[0])
  A = sp.solve(x*M[0][0]+M[0][1]*B+M[0][2]*C-M[0][3],x)
  A = float(A[0])
  return A,B,C


def gauss_jordan2x2(M):
  x = sp.Symbol("x")
  if M[1,0] != 0 and M[0,0] !=0 :
    val = sp.solve(x*M[0,0]-M[1,0],x)
    val = val[0]
    M = sum_filas_escalar(M,2,1,1,-val)
    return M
  elif M[0,0] == 0 and M[0,1] == 0 and M[1,0] == 0 and M[1,1] !=0:
    return M
  elif M[0,0] !=0 and M[0,1] == 0 and M[1,0] == 0 and M[1,1] == 0:
    return M
  elif M[0,0] == 0 and M[0,1]!=0 and M[1,0] == 0 and M[1,1] == 0:
    return M
  elif M[0,0] == 0 and M[1,0] !=0:
    M = intercambio(M,1,2)
    return M
  elif M[0,0] !=0 and M[1,1] !=0 and M[1,0] == 0 and M[0,1] == 0:
    return M
  elif M[0,0] !=0 and M[0,1] == 0:
    M = intercambio(M,1,2)
    val = sp.solve(x*M[0,0]-M[1,0],x)
    val = val[0]
    M = sum_filas_escalar(M,2,1,1,-val)
    return M
  elif M[0,0] != 0 and M[1,0] == 0:
    return M
  elif M[0,0] == 0 and M[0,1] == 0 and M[1,0] !=0:
    M = intercambio(M,1,2)
    return M
  elif M[0,0] == 0 and M[0,1] !=0 and M[1,0] == 0 and M[1,1] !=0:
    val = sp.solve(x*M[0,1]-M[1,1],x)
    val = val[0]
    M = sum_filas_escalar(M,2,1,1,-val)
    return M
  return M



In [69]:
## Gauss jordan Linealmente dependiente.
def gauss_jordanLD3x3(M):
  x = sp.Symbol("x")
  gauss = gauss_jordan(M)
  dimM = np.shape(M)
  vect = np.zeros(dimM[0])
  eps = 1e-6
  if gauss[2,2] <= eps and gauss[1,1]!=0:
    z = np.random.random(1)
    y = sp.solve(x*gauss[1][1]+gauss[1][2]*z,x)
    y = y[x]
    y = np.array([y])
    val1 = gauss[0][1]*y
    val2 = gauss[0][2]*z
    cte = val1+val2
    x1 = sp.solve(x*gauss[0][0]+cte,x)
    vect = np.zeros((1,3))
    vect[0,0] = x1[x]
    vect[0,1] = y
    vect[0,2] = z
    return vect
  elif  gauss[2,2] <= eps and gauss[1,1] <= eps:
    z = 0
    y = np.random.random(1)
    x1 = sp.solve(x*gauss[0,0]+y*gauss[0,1],x)
    vect = np.zeros((1,3))
    vect[0,0] = x1[x]
    vect[0,1] = y
    vect[0,2] = z
    return vect

def gauss_jordanLD2x2(M):
  x = sp.Symbol("x")
  gauss = gauss_jordan2x2(M)
  y = np.random.random(1)
  x1 = sp.solve(x*gauss[0,0]+y*gauss[0,1],x)
  x1 = x1[x]
  vect = np.zeros((2,1))
  vect[0,0] = x1
  vect[1,0] = y
  return vect

In [88]:
## en esta linea vamos a generalizar la idea anterior para hallar los vectores propios

def autovectores(M):
  eigenvalues = autovalores(M)
  I = np.identity(np.shape(M)[0])
  matriz_solve = M-(eigenvalues[0]*I)
  eig_vect0 = gauss_jordanLD3x3(matriz_solve)
  matriz_solve1 = M - (eigenvalues[1]*I)
  eig_vect1 = gauss_jordanLD3x3(matriz_solve1)
  matriz_solve2 = M - (eigenvalues[2]*I)
  eig_vect2 = gauss_jordanLD3x3(matriz_solve2)
  P = np.array([eig_vect0,eig_vect1,eig_vect2])
  return P

def matriz_autovalores2x2(M):
  eigenvalues = autovalores2x2(M)
  Matriz = np.zeros((2,2))
  for i in range(len(eigenvalues)):
    Matriz[i,i] = eigenvalues[i]
  return Matriz

def autovectores2x2(M):
  eigenvalues = autovalores2x2(M)
  I = np.identity(np.shape(M)[0])
  matriz_res = M - eigenvalues[0]*I
  eigen_vect0 = gauss_jordanLD2x2(matriz_res)
  matriz_res1 = M - eigenvalues[1]*I
  eigen_vect1 = gauss_jordanLD2x2(matriz_res1)
  matriz_vects = np.array([eigen_vect0,eigen_vect1])
  return matriz_vects

def matriz_autovectores2x2(M):
  matriz_vects = autovectores2x2(M)
  matriz_autovectores = np.zeros((2,2))
  for i in range(2):
    for j in range(2):
      matriz_autovectores[j,i] = matriz_vects[i][j]
  matriz_autovectores
  return matriz_autovectores

def matriz_autovectores2x2complex(M):
  matriz_autovectores = np.empty((2,2),dtype = complex)
  matriz_vects = autovectores2x2(M)
  return matriz_vects

def matriz_autovectores(M):
  vectors = autovectores(M)
  P_ = np.zeros((3,3))
  eigenvalues = autovalores(M)
  for i in range(len(eigenvalues)):
    for j in range(len(eigenvalues)):
      P_[j,i] = vectors[i][0][j]
  return P_

def matriz_autovalores(M):
  eigenvalues = autovalores(M)
  P = np.zeros((3,3))
  for i in range(len(eigenvalues)):
    P[i,i] = eigenvalues[i]
  return P

def diagonal3x3(M):
  det = det3x3(M)
  if det!=0:
    U = np.asmatrix(matriz_autovectores(M))
    P = np.asmatrix(matriz_autovalores(M))
    invU = U.I
    val = invU@M@U
    return val
  else:
    msg = "no se puede diagonalizar"
    return msg

def diagonal2x2(M):
  det = det2x2(M)
  if det!=0:
    U = np.asmatrix(matriz_autovectores2x2(M))
    invU = U.I
    val = invU@M@U
    return val
  else:
    msg = "no se puede diagonalizar"
    return msg




In [99]:
M = np.array([[1,-1,4],
              [3,2,-1],
              [2,1,-1]

              ])
U = np.asmatrix(matriz_autovectores(M))
P = np.asmatrix(matriz_autovalores(M))

D = U.I@M@U
diagonal3x3(M),U@P@U.I

(matrix([[-2.00000000e+00, -4.33597378e-14, -1.41855310e-14],
         [-5.82278738e-17,  1.00000000e+00,  3.73260614e-16],
         [-5.26969898e-17,  1.80399170e-15,  3.00000000e+00]]),
 matrix([[ 1., -1.,  4.],
         [ 3.,  2., -1.],
         [ 2.,  1., -1.]]))

In [105]:
M10 = np.array([ [3,-5],
               [1,-1]
                     ])
U_, P_ = np.linalg.eig(M10)
diagonal = np.diag(U_)
P_ = np.asmatrix(P_)

In [108]:
M10 = np.asmatrix(M10)
D_ = P_.I@M10@P_
## diagonalización
D_

matrix([[ 1.00000000e+00+1.00000000e+00j,
         -1.11022302e-16-3.88578059e-16j],
        [-5.55111512e-17+4.99600361e-16j,
          1.00000000e+00-1.00000000e+00j]])